### ISSUE TITLE
TLS handshaking: SSL_accept() failed: 

### ISSUE THREAD

**Issue by voti** [RainLoop/rainloop-webmail#1346]
**Can not login!!!**

**RainLoop version, browser, OS:**
Rainloop Community edition 
v1.10.5.192 (06.11.2016)  
Chrome browser
Windows 10
**Server**
Nginx
PHP7.0
**Expected behavior and actual behavior:**
login my mailserver
**Steps to reproduce the problem:**
login
**Logs or screenshots:**
login with Rainloop
mailserver log
```
mail    | Feb 22 10:59:41 mx dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=xxx.xxx.xxx.xxx, lip=192.168.32.2, TLS handshaking: SSL_accept() failed: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher, session=<WOy5ZBxJpACvfiWQ>
```
login with thunderbird
mailserver log
```
mail    | Feb 22 08:14:49 mx dovecot: imap-login: Login: user=<xxx@xxx.com>, method=PLAIN, rip=xxx.xxx.xxx.xxx, lip=192.168.32.2, mpid=1503, TLS, session=<JEoaFxpJnwC3lSNy>
```

[Mailserver ](https://github.com/tomav/docker-mailserver)config

```
version: '2'

services:
  mail:
    restart: always
    image: tvial/docker-mailserver:latest
    # build: .
    hostname: mx
    domainname: xxx.com
    container_name: mail
    environment:
      - SSL_TYPE=letsencrypt
      - POSTMASTER_ADDRESS=postmaster@xxx.com
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./config/:/tmp/docker-mailserver/
      - /etc/letsencrypt:/etc/letsencrypt
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```
